"""Add setup fields

Revision ID: 561ac151367f
Revises: b78433edf723
Create Date: 2026-06-12 12:23:18.503425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '561ac151367f'
down_revision: Union[str, None] = 'b78433edf723'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('institutions', sa.Column('shortcode', sa.String(length=20), nullable=True))
    op.add_column('institutions', sa.Column('tagline', sa.String(length=500), nullable=True))
    op.add_column('institutions', sa.Column('country', sa.String(length=100), nullable=True))
    op.add_column('institutions', sa.Column('timezone', sa.String(length=100), nullable=True))
    op.add_column('institutions', sa.Column('accent_color', sa.String(length=10), nullable=True))
    op.add_column('institutions', sa.Column('admin_name', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('display_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'display_name')
    op.drop_column('institutions', 'admin_name')
    op.drop_column('institutions', 'accent_color')
    op.drop_column('institutions', 'timezone')
    op.drop_column('institutions', 'country')
    op.drop_column('institutions', 'tagline')
    op.drop_column('institutions', 'shortcode')
    # ### end Alembic commands ###
