"""Add preferences and login tracking to user

Revision ID: c8b864021405
Revises: a1b2c3d4e5f6
Create Date: 2026-06-19 00:14:25.532971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8b864021405'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_class_schedules_course_id', table_name='class_schedules')
    op.add_column('users', sa.Column('preferences', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('last_login_device', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('last_login_location', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_login_location')
    op.drop_column('users', 'last_login_device')
    op.drop_column('users', 'preferences')
    op.create_index('ix_class_schedules_course_id', 'class_schedules', ['course_id'], unique=False)
    # ### end Alembic commands ###
